### ISSUE TITLE
Need to Add Primary and Secondary Colors Back

### ISSUE THREAD

**Issue by KamathVishak96** [varunsat/creyo-issues#1]
Fields and their keys will look like this:
1. Primary Color - primaryColor
2. Primary Color Dark - primaryDarkColor
3. Primary Color Light - primaryLightColor
4. Secondary Color - secondaryColor
5. Secondary Color Dark - secondaryDarkColor
6. Secondary Color Light - secondaryLightColor

**Comment by raja-creoit** [comment]
Done
